baseURL = 'https://www.amazon.it/'
URLAffiliateElement = '/?tag='
URLfinalElement = '&psc=1'
telegramToken = '6273547056:AAHb_StXIsyakpC023tE2Zf1CWVmBL-flTs'
key = ""
systemOne = "Linux"
days = 2
channel_id = ''
affiliateCode = ''
channelLink = ''
URLS = None